site_name: MyMovieDatabase
site_description: A tool for managing your movie ratings.
theme:
  name: readthedocs
markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
